### ISSUE TITLE
Sine example is broken

### ISSUE THREAD

**Issue by ul** [klingtnet/rsoundio#6]
Hi! I'm new to both Rust and libsoundio, and I've failed to fix this by myself. When I do `cargo run --example sine` I see

```
λ cargo run --example sine
     Running `target/debug/examples/sine`
Connected to backend: PulseAudio
Using output device: Built-in audio Analog stereo
Output format: float 32-bit LE
Sample rate: 48000
SW latency: 0
Output channel layout: Stereo
Underflow in sine occured!
Underflow in sine occured!
Pause for 1s
Unpausing
```

with proper delays between pause messages, but I only hear a very short piece of sound (I guess it's a one or a couple of buffers of 1024 samples).

**Comment by klingtnet** [comment]
Hi @ul!
Try to increase the `BUF_SIZE` constant in the [write callback](https://github.com/klingtnet/rsoundio/blob/master/examples/sine.rs#L51) to 4096 samples or make it dynamic by using the `max_frame_count` that you get on each callback. I'm using libsoundio solely with JACK because it's nearly impossible to get small latencies with PulseAudio.

**Comment by ul** [comment]
I've tried to change `BUF_SIZE`, but it definitely plays only buffer available first time callback is called. The larger `BUF_SIZE` is, the longer is sound, but then it stops anyway before program ends. `min_frame_count` and `max_frame_count` are weird:

`println!("{}/{}", min_frame_count, max_frame_count);`

```
SW latency: 0
Output channel layout: Stereo
0/96000
0/175952
Underflow in sine occured!
Underflow in sine occured!
0/229568
0/222448
0/274720
0/267592
0/260392
Pause for 1s
Unpausing
0/270880
0/263928
```

But okay, if it's PulseAudio's problem, I'll try with JACK and then report back. But it is strange, PortAudio works with PulseAudio for me even on relatively small latencies. After reading libsoundio advertising I thought that it will too =)

**Comment by ul** [comment]
Yep, with JACK works fine. Sorry for the noise, it's all PulseAudio weirdness.

**Comment by klingtnet** [comment]
PulseAudio will start with a relatively large `max_frame_count` which is decreased on every callback until it reaches some minimal size, ~350 samples on my machine. The sine example from the `libsound.io` sources also works fine with PulseAudio so there has to be some problem in my Rust binding but I haven't figured out the problem yet and I didn't do anything special regard PA.

**Comment by ul** [comment]
But now pause don't stop sound =(

**Comment by klingtnet** [comment]
Pause is not supported for JACK.

**Comment by ul** [comment]
Got it, thank you!

**Comment by klingtnet** [comment]
You're welcome.

**Comment by ul** [comment]
My problem with PulseAudio might be connected to latency having strictly 0 value. Probably setting it manually will fix the problem, but as far as I can see, you have no bindings to set latency by hands, only to get it.

**Comment by klingtnet** [comment]
The latency value will be set by libsoundio [when you open a device](http://libsound.io/doc-1.1.0/structSoundIoOutStream.html#a20aac1422d3cc64b679616bb8447f06d), I don't think that it's intended to be set manually.

**Comment by klingtnet** [comment]
I will add a setter for this and make a new release.

**Comment by klingtnet** [comment]
@ul calling `out.clear_buffer();` [before pausing the stream](https://github.com/klingtnet/rsoundio/blob/master/examples/sine.rs#L84) fixes the PA issues, at least on my machine. I would be happy if you can try this, too.

**Comment by klingtnet** [comment]
PS: I've added a `set_latency` method to the output stream but I have to make a bit testing before releasing this.

**Comment by ul** [comment]
`out.clear_buffer();` gives one more pulse of sound on my machine, but doesn't make it continuous.

**Comment by klingtnet** [comment]
Hmm, this is strange. I will keep you updated if I found a fix for the problem.
